services:
  landing-backend:
    build: .
    container_name: landing-backend
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    # Opcionales: host/port SMTP distintos de Gmail
    # environment:
    #   MAIL_HOST: smtp.tucorreo.com
    #   MAIL_PORT: "587"
    restart: unless-stopped